name: Snyk Container

on:
  push:
    branches: ["master"]
    paths-ignore:
     - ".github/**"
     - "**.md"
  pull_request:
    branches: ["master"]
    paths-ignore:
     - ".github/**"
     - "**.md"
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
